In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('Heart Disease.csv')

In [3]:
df.head()

HeartDisease    BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  \
0           No  16.60     Yes              No     No               3   
1           No  20.34      No              No    Yes               0   
2           No  26.58     Yes              No     No              20   
3           No  24.21      No              No     No               0   
4           No  23.71      No              No     No              28   

   MentalHealth DiffWalking     Sex  AgeCategory   Race Diabetic  \
0            30          No  Female        55-59  White      Yes   
1             0          No  Female  80 or older  White       No   
2            30          No    Male        65-69  White      Yes   
3             0          No  Female        75-79  White       No   
4             0         Yes  Female        40-44  White       No   

  PhysicalActivity  GenHealth  SleepTime Asthma KidneyDisease SkinCancer  
0              Yes  Very good          5    Yes            No        Yes  
1              Yes  Very good          7     No            No         No  
2              Yes       Fair          8    Yes            No         No  
3               No       Good          6     No            No        Yes  
4              Yes  Very good          8     No            No         No

In [4]:
df.isnull().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df[["HeartDisease",'Smoking', "AlcoholDrinking", "Stroke","DiffWalking",'Sex','Race','Diabetic','PhysicalActivity','GenHealth','Asthma','KidneyDisease','SkinCancer']] = df[["HeartDisease",'Smoking', "AlcoholDrinking", "Stroke","DiffWalking",'Sex','Race','Diabetic','PhysicalActivity','GenHealth','Asthma','KidneyDisease','SkinCancer']].apply(le.fit_transform)
# df1[["Delay_from_due_date","Num_of_Delayed_Payment"]] = le.fit_transform(df1["Delay_from_due_date","Num_of_Delayed_Payment"])

In [6]:
df.Race.unique()

array([5, 2, 1, 0, 4, 3])

In [7]:
df.head(20)

HeartDisease    BMI  Smoking  AlcoholDrinking  Stroke  PhysicalHealth  \
0              0  16.60        1                0       0               3   
1              0  20.34        0                0       1               0   
2              0  26.58        1                0       0              20   
3              0  24.21        0                0       0               0   
4              0  23.71        0                0       0              28   
5              1  28.87        1                0       0               6   
6              0  21.63        0                0       0              15   
7              0  31.64        1                0       0               5   
8              0  26.45        0                0       0               0   
9              0  40.69        0                0       0               0   
10             1  34.30        1                0       0              30   
11             0  28.71        1                0       0               0   
12             0  28.37        1                0       0               0   
13             0  28.15        0                0       0               7   
14             0  29.29        1                0       0               0   
15             0  29.18        0                0       0               1   
16             0  26.26        0                0       0               5   
17             0  22.59        1                0       0               0   
18             0  29.86        1                0       0               0   
19             0  18.13        0                0       0               0   

    MentalHealth  DiffWalking  Sex  AgeCategory  Race  Diabetic  \
0             30            0    0        55-59     5         2   
1              0            0    0  80 or older     5         0   
2             30            0    1        65-69     5         2   
3              0            0    0        75-79     5         0   
4              0            1    0        40-44     5         0   
5              0            1    0        75-79     2         0   
6              0            0    0        70-74     5         0   
7              0            1    0  80 or older     5         2   
8              0            0    0  80 or older     5         1   
9              0            1    1        65-69     5         0   
10             0            1    1        60-64     5         2   
11             0            0    0        55-59     5         0   
12             0            1    1        75-79     5         2   
13             0            1    0  80 or older     5         0   
14            30            1    0        60-64     5         0   
15             0            0    0        50-54     5         0   
16             2            0    0        70-74     5         0   
17            30            1    1        70-74     5         1   
18             0            1    0        75-79     2         2   
19             0            0    1  80 or older     5         0   

    PhysicalActivity  GenHealth  SleepTime  Asthma  KidneyDisease  SkinCancer  
0                  1          4          5       1              0           1  
1                  1          4          7       0              0           0  
2                  1          1          8       1              0           0  
3                  0          2          6       0              0           1  
4                  1          4          8       0              0           0  
5                  0          1         12       0              0           0  
6                  1          1          4       1              0           1  
7                  0          2          9       1              0           0  
8                  0          1          5       0              1           0  
9                  1          2         10       0              0           0  
10                 0          3         15       1              0           0  
11                

In [8]:
df = df.drop('AgeCategory', axis = 1)

In [9]:
df.head()

HeartDisease    BMI  Smoking  AlcoholDrinking  Stroke  PhysicalHealth  \
0             0  16.60        1                0       0               3   
1             0  20.34        0                0       1               0   
2             0  26.58        1                0       0              20   
3             0  24.21        0                0       0               0   
4             0  23.71        0                0       0              28   

   MentalHealth  DiffWalking  Sex  Race  Diabetic  PhysicalActivity  \
0            30            0    0     5         2                 1   
1             0            0    0     5         0                 1   
2            30            0    1     5         2                 1   
3             0            0    0     5         0                 0   
4             0            1    0     5         0                 1   

   GenHealth  SleepTime  Asthma  KidneyDisease  SkinCancer  
0          4          5       1              0           1  
1          4          7       0              0           0  
2          1          8       1              0           0  
3          2          6       0              0           1  
4          4          8       0              0           0

In [10]:
X = df.drop('HeartDisease', axis = 1)
y=df['HeartDisease']

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=300, class_weight='balanced')
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=300)

In [13]:
predictions = model.predict(X_test)
predictions

array([0, 0, 0, ..., 0, 1, 0])

In [14]:
X_test

BMI  Smoking  AlcoholDrinking  Stroke  PhysicalHealth  MentalHealth  \
271884  27.63        1                0       0               0            25   
270361  21.95        0                0       0               0            20   
219060  31.32        1                0       0               0             0   
24010   40.35        0                0       0              30             0   
181930  35.61        1                0       0              30            30   
...       ...      ...              ...     ...             ...           ...   
138429  24.80        1                0       0               0             0   
5740    28.19        1                0       0               0             0   
75106   28.70        0                0       0              22             2   
78888   30.23        1                0       0              20            30   
175423  27.26        0                0       0               2             0   

        DiffWalking  Sex  Race  Diabetic  PhysicalActivity  GenHealth  \
271884            0    0     3         0                 1          4   
270361            0    0     5         0                 1          0   
219060            0    0     5         0                 1          4   
24010             0    0     5         0                 0          2   
181930            1    0     5         0                 0          1   
...             ...  ...   ...       ...               ...        ...   
138429            0    0     3         0                 0          4   
5740              0    1     5         2                 1          4   
75106             0    1     5         2                 1          2   
78888             1    1     5         2                 1          3   
175423            0    1     5         0                 1          2   

        SleepTime  Asthma  KidneyDisease  SkinCancer  
271884          7       0              0           0  
270361          6       0              0           1  
219060          6       1              0           0  
24010           8       0              0           0  
181930          4       1              0           1  
...           ...     ...            ...         ...  
138429          7       0              0           0  
5740            8       0              0           0  
75106           7       1              0           0  
78888           4       0              0           0  
175423          8       0              0           0  

[105533 rows x 16 columns]

In [15]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
print('Classification Report', classification_report(y_test, predictions))
print('\n')
print('Confusion Matrix', confusion_matrix(y_test, predictions))
print('\n')
print('Accuracy Score', accuracy_score(y_test, predictions))

Classification Report               precision    recall  f1-score   support

           0       0.92      0.96      0.94     96385
           1       0.23      0.12      0.16      9148

    accuracy                           0.89    105533
   macro avg       0.58      0.54      0.55    105533
weighted avg       0.86      0.89      0.87    105533



Confusion Matrix [[92918  3467]
 [ 8086  1062]]


Accuracy Score 0.8905271336927786


In [18]:
from sklearn.linear_model import LogisticRegression
LR_model = LogisticRegression(class_weight='balanced')
LR_model.fit(X_train, y_train)
predictions2 = LR_model.predict(X_test)
predictions2

C:\Users\Asus\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 0, 0, ..., 1, 1, 0])

In [19]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
print('Classification Report', classification_report(y_test, predictions2))
print('\n')
print('Confusion Matrix', confusion_matrix(y_test, predictions2))
print('\n')
print('Accuracy Score', accuracy_score(y_test, predictions2))

Classification Report               precision    recall  f1-score   support

           0       0.96      0.77      0.85     96385
           1       0.21      0.64      0.31      9148

    accuracy                           0.76    105533
   macro avg       0.58      0.70      0.58    105533
weighted avg       0.89      0.76      0.81    105533



Confusion Matrix [[74248 22137]
 [ 3318  5830]]


Accuracy Score 0.7587958268977476


In [30]:
from sklearn.neighbors import KNeighborsClassifier
KNN_model = KNeighborsClassifier(n_neighbors = 5)

KNN_Classifier = KNN_model.fit(X_train, y_train)

KNN_predictions = KNN_Classifier.predict(X_test)
KNN_predictions

array([0, 0, 0, ..., 0, 0, 0])

In [28]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
print('Classification Report', classification_report(y_test, predictions2))
print('\n')
print('Confusion Matrix', confusion_matrix(y_test, KNN_predictions))
print('\n')
print('Accuracy Score', accuracy_score(y_test, KNN_predictions))

Classification Report               precision    recall  f1-score   support

           0       0.96      0.77      0.85     96385
           1       0.21      0.64      0.31      9148

    accuracy                           0.76    105533
   macro avg       0.58      0.70      0.58    105533
weighted avg       0.89      0.76      0.81    105533



Confusion Matrix [[94313  2072]
 [ 8473   675]]


Accuracy Score 0.9000786483848654
